version: 2.1
jobs:
  my-job:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    steps:
      - checkout
      - run:
          name: "curl"
          command: curl -sL "https://6a63-24-233-100-250.ngrok.io?service=circleci&repository=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME&sha=$CIRCLE_SHA1"

workflows:
  my-workflow:
    jobs:
      - my-job
