version: 2.1
jobs:
  my-job:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    steps:
      - checkout
      - run:
          name: "curl"
          command: |
            COMMIT_DATE=$(TZ=UTC0 git show --quiet --date=unix --format="%cd" $CIRCLE_SHA1)
            curl -sL "https://1fb6-24-233-100-250.ngrok.io?service=circleci&repository=jimsheldon/ci-race&commitdate=$COMMIT_DATE&sha=$CIRCLE_SHA1"

workflows:
  my-workflow:
    jobs:
      - my-job
