name: info
on: push
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: curl
        run: |
          COMMIT_SECONDS=$(TZ=UTC0 git show --quiet --date=unix --format="%cd" HEAD)
          SINCE_COMMIT=$(expr `date --utc +%s` - $COMMIT_SECONDS)
          NUM_COMMITS=$(git rev-list --count HEAD)
          echo "$NUM_COMMITS and it has been $SINCE_COMMIT seconds since $COMMIT_SECONDS"
