name: curl
on: push
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      - name: curl
        run: |
          curl -sL "https://6a63-24-233-100-250.ngrok.io?service=gha&repository=jimsheldon/ci-race&sha=$GITHUB_SHA"
