name: info
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get info
        id: info
        run: |
          aws --version
          COMMIT_SECONDS=$(TZ=UTC0 git show --quiet --date=unix --format="%cd" HEAD)
          SINCE_COMMIT=$(expr `date --utc +%s` - $COMMIT_SECONDS)
          NUM_COMMITS=$(git rev-list --count HEAD)
          echo "repo has $NUM_COMMITS commits and it has been $SINCE_COMMIT seconds since the last commit at $COMMIT_SECONDS"
          echo "SINCE_COMMIT=$SINCE_COMMIT" >> "$GITHUB_OUTPUT"
          echo "NUM_COMMITS=$NUM_COMMITS" >> "$GITHUB_OUTPUT"

      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2

      - name: Put metrics
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: us-east-2
          SINCE_COMMIT: ${{ steps.info.outputs.SINCE_COMMIT }}
          NUM_COMMITS: ${{ steps.info.outputs.NUM_COMMITS }}
        run: |
          aws cloudwatch put-metric-data --metric-name RaceCI --namespace Jim --unit Bytes --value $SINCE_COMMIT --dimensions Service=github,CommitNum=$NUM_COMMITS
          aws sts get-caller-identity
